// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package types

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for GroupVersionResource
func (this *GroupVersionResource) MarshalJSON() ([]byte, error) {
	str, err := GroupVersionMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GroupVersionResource
func (this *GroupVersionResource) UnmarshalJSON(b []byte) error {
	return GroupVersionUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GroupVersionKind
func (this *GroupVersionKind) MarshalJSON() ([]byte, error) {
	str, err := GroupVersionMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GroupVersionKind
func (this *GroupVersionKind) UnmarshalJSON(b []byte) error {
	return GroupVersionUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for GroupVersionResourceIdentifier
func (this *GroupVersionResourceIdentifier) MarshalJSON() ([]byte, error) {
	str, err := GroupVersionMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for GroupVersionResourceIdentifier
func (this *GroupVersionResourceIdentifier) UnmarshalJSON(b []byte) error {
	return GroupVersionUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	GroupVersionMarshaler   = &jsonpb.Marshaler{}
	GroupVersionUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
