// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package types

import (
	jsonpb "github.com/golang/protobuf/jsonpb"
)

var (
	GroupVersionMarshaler   = &jsonpb.Marshaler{}
	GroupVersionUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
