// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: types/group_version.proto

package types

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GroupVersionResource with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GroupVersionResource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GroupVersionResource with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GroupVersionResourceMultiError, or nil if none found.
func (m *GroupVersionResource) ValidateAll() error {
	return m.validate(true)
}

func (m *GroupVersionResource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Group

	// no validation rules for Version

	// no validation rules for Resource

	if len(errors) > 0 {
		return GroupVersionResourceMultiError(errors)
	}

	return nil
}

// GroupVersionResourceMultiError is an error wrapping multiple validation
// errors returned by GroupVersionResource.ValidateAll() if the designated
// constraints aren't met.
type GroupVersionResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GroupVersionResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GroupVersionResourceMultiError) AllErrors() []error { return m }

// GroupVersionResourceValidationError is the validation error returned by
// GroupVersionResource.Validate if the designated constraints aren't met.
type GroupVersionResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GroupVersionResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GroupVersionResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GroupVersionResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GroupVersionResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GroupVersionResourceValidationError) ErrorName() string {
	return "GroupVersionResourceValidationError"
}

// Error satisfies the builtin error interface
func (e GroupVersionResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGroupVersionResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GroupVersionResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GroupVersionResourceValidationError{}

// Validate checks the field values on GroupVersionKind with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GroupVersionKind) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GroupVersionKind with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GroupVersionKindMultiError, or nil if none found.
func (m *GroupVersionKind) ValidateAll() error {
	return m.validate(true)
}

func (m *GroupVersionKind) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Group

	// no validation rules for Version

	// no validation rules for Kind

	if len(errors) > 0 {
		return GroupVersionKindMultiError(errors)
	}

	return nil
}

// GroupVersionKindMultiError is an error wrapping multiple validation errors
// returned by GroupVersionKind.ValidateAll() if the designated constraints
// aren't met.
type GroupVersionKindMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GroupVersionKindMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GroupVersionKindMultiError) AllErrors() []error { return m }

// GroupVersionKindValidationError is the validation error returned by
// GroupVersionKind.Validate if the designated constraints aren't met.
type GroupVersionKindValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GroupVersionKindValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GroupVersionKindValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GroupVersionKindValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GroupVersionKindValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GroupVersionKindValidationError) ErrorName() string { return "GroupVersionKindValidationError" }

// Error satisfies the builtin error interface
func (e GroupVersionKindValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGroupVersionKind.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GroupVersionKindValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GroupVersionKindValidationError{}

// Validate checks the field values on GroupVersionResourceIdentifier with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GroupVersionResourceIdentifier) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GroupVersionResourceIdentifier with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GroupVersionResourceIdentifierMultiError, or nil if none found.
func (m *GroupVersionResourceIdentifier) ValidateAll() error {
	return m.validate(true)
}

func (m *GroupVersionResourceIdentifier) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch m.Option.(type) {

	case *GroupVersionResourceIdentifier_Enum:
		// no validation rules for Enum

	case *GroupVersionResourceIdentifier_Custom:

		if all {
			switch v := interface{}(m.GetCustom()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GroupVersionResourceIdentifierValidationError{
						field:  "Custom",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GroupVersionResourceIdentifierValidationError{
						field:  "Custom",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCustom()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GroupVersionResourceIdentifierValidationError{
					field:  "Custom",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GroupVersionResourceIdentifierMultiError(errors)
	}

	return nil
}

// GroupVersionResourceIdentifierMultiError is an error wrapping multiple
// validation errors returned by GroupVersionResourceIdentifier.ValidateAll()
// if the designated constraints aren't met.
type GroupVersionResourceIdentifierMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GroupVersionResourceIdentifierMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GroupVersionResourceIdentifierMultiError) AllErrors() []error { return m }

// GroupVersionResourceIdentifierValidationError is the validation error
// returned by GroupVersionResourceIdentifier.Validate if the designated
// constraints aren't met.
type GroupVersionResourceIdentifierValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GroupVersionResourceIdentifierValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GroupVersionResourceIdentifierValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GroupVersionResourceIdentifierValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GroupVersionResourceIdentifierValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GroupVersionResourceIdentifierValidationError) ErrorName() string {
	return "GroupVersionResourceIdentifierValidationError"
}

// Error satisfies the builtin error interface
func (e GroupVersionResourceIdentifierValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGroupVersionResourceIdentifier.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GroupVersionResourceIdentifierValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GroupVersionResourceIdentifierValidationError{}
