// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package types

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using CustomSelector within kubernetes types, where deepcopy-gen is used.
func (in *CustomSelector) DeepCopyInto(out *CustomSelector) {
	p := proto.Clone(in).(*CustomSelector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomSelector. Required by controller-gen.
func (in *CustomSelector) DeepCopy() *CustomSelector {
	if in == nil {
		return nil
	}
	out := new(CustomSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CustomSelector. Required by controller-gen.
func (in *CustomSelector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListOptions within kubernetes types, where deepcopy-gen is used.
func (in *ListOptions) DeepCopyInto(out *ListOptions) {
	p := proto.Clone(in).(*ListOptions)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListOptions. Required by controller-gen.
func (in *ListOptions) DeepCopy() *ListOptions {
	if in == nil {
		return nil
	}
	out := new(ListOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListOptions. Required by controller-gen.
func (in *ListOptions) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
