// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package types

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using NamespaceName within kubernetes types, where deepcopy-gen is used.
func (in *NamespaceName) DeepCopyInto(out *NamespaceName) {
	p := proto.Clone(in).(*NamespaceName)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceName. Required by controller-gen.
func (in *NamespaceName) DeepCopy() *NamespaceName {
	if in == nil {
		return nil
	}
	out := new(NamespaceName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceName. Required by controller-gen.
func (in *NamespaceName) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
