// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package types

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using OwnerReference within kubernetes types, where deepcopy-gen is used.
func (in *OwnerReference) DeepCopyInto(out *OwnerReference) {
	p := proto.Clone(in).(*OwnerReference)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnerReference. Required by controller-gen.
func (in *OwnerReference) DeepCopy() *OwnerReference {
	if in == nil {
		return nil
	}
	out := new(OwnerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new OwnerReference. Required by controller-gen.
func (in *OwnerReference) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ObjectMeta within kubernetes types, where deepcopy-gen is used.
func (in *ObjectMeta) DeepCopyInto(out *ObjectMeta) {
	p := proto.Clone(in).(*ObjectMeta)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectMeta. Required by controller-gen.
func (in *ObjectMeta) DeepCopy() *ObjectMeta {
	if in == nil {
		return nil
	}
	out := new(ObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ObjectMeta. Required by controller-gen.
func (in *ObjectMeta) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Selector within kubernetes types, where deepcopy-gen is used.
func (in *Selector) DeepCopyInto(out *Selector) {
	p := proto.Clone(in).(*Selector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Selector. Required by controller-gen.
func (in *Selector) DeepCopy() *Selector {
	if in == nil {
		return nil
	}
	out := new(Selector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Selector. Required by controller-gen.
func (in *Selector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using LabelSelector within kubernetes types, where deepcopy-gen is used.
func (in *LabelSelector) DeepCopyInto(out *LabelSelector) {
	p := proto.Clone(in).(*LabelSelector)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelector. Required by controller-gen.
func (in *LabelSelector) DeepCopy() *LabelSelector {
	if in == nil {
		return nil
	}
	out := new(LabelSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelector. Required by controller-gen.
func (in *LabelSelector) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using LabelSelectorRequirement within kubernetes types, where deepcopy-gen is used.
func (in *LabelSelectorRequirement) DeepCopyInto(out *LabelSelectorRequirement) {
	p := proto.Clone(in).(*LabelSelectorRequirement)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelectorRequirement. Required by controller-gen.
func (in *LabelSelectorRequirement) DeepCopy() *LabelSelectorRequirement {
	if in == nil {
		return nil
	}
	out := new(LabelSelectorRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelectorRequirement. Required by controller-gen.
func (in *LabelSelectorRequirement) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
