// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package types

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for OwnerReference
func (this *OwnerReference) MarshalJSON() ([]byte, error) {
	str, err := ObjectMetaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for OwnerReference
func (this *OwnerReference) UnmarshalJSON(b []byte) error {
	return ObjectMetaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ObjectMeta
func (this *ObjectMeta) MarshalJSON() ([]byte, error) {
	str, err := ObjectMetaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ObjectMeta
func (this *ObjectMeta) UnmarshalJSON(b []byte) error {
	return ObjectMetaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Selector
func (this *Selector) MarshalJSON() ([]byte, error) {
	str, err := ObjectMetaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Selector
func (this *Selector) UnmarshalJSON(b []byte) error {
	return ObjectMetaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LabelSelector
func (this *LabelSelector) MarshalJSON() ([]byte, error) {
	str, err := ObjectMetaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LabelSelector
func (this *LabelSelector) UnmarshalJSON(b []byte) error {
	return ObjectMetaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for LabelSelectorRequirement
func (this *LabelSelectorRequirement) MarshalJSON() ([]byte, error) {
	str, err := ObjectMetaMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for LabelSelectorRequirement
func (this *LabelSelectorRequirement) UnmarshalJSON(b []byte) error {
	return ObjectMetaUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ObjectMetaMarshaler   = &jsonpb.Marshaler{}
	ObjectMetaUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
