// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for VirtualMachinePowerStateRequest
func (this *VirtualMachinePowerStateRequest) MarshalJSON() ([]byte, error) {
	str, err := VirtualmachineMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for VirtualMachinePowerStateRequest
func (this *VirtualMachinePowerStateRequest) UnmarshalJSON(b []byte) error {
	return VirtualmachineUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	VirtualmachineMarshaler   = &jsonpb.Marshaler{}
	VirtualmachineUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
