// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: management/virtualmachine/v1alpha1/virtualmachine.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VirtualMachineManagementClient is the client API for VirtualMachineManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VirtualMachineManagementClient interface {
	VirtualMachinePowerState(ctx context.Context, in *VirtualMachinePowerStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type virtualMachineManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewVirtualMachineManagementClient(cc grpc.ClientConnInterface) VirtualMachineManagementClient {
	return &virtualMachineManagementClient{cc}
}

func (c *virtualMachineManagementClient) VirtualMachinePowerState(ctx context.Context, in *VirtualMachinePowerStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/vink.kubevm.io.apis.management.virtualmachine.v1alpha1.VirtualMachineManagement/VirtualMachinePowerState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualMachineManagementServer is the server API for VirtualMachineManagement service.
// All implementations must embed UnimplementedVirtualMachineManagementServer
// for forward compatibility
type VirtualMachineManagementServer interface {
	VirtualMachinePowerState(context.Context, *VirtualMachinePowerStateRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedVirtualMachineManagementServer()
}

// UnimplementedVirtualMachineManagementServer must be embedded to have forward compatible implementations.
type UnimplementedVirtualMachineManagementServer struct {
}

func (UnimplementedVirtualMachineManagementServer) VirtualMachinePowerState(context.Context, *VirtualMachinePowerStateRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VirtualMachinePowerState not implemented")
}
func (UnimplementedVirtualMachineManagementServer) mustEmbedUnimplementedVirtualMachineManagementServer() {
}

// UnsafeVirtualMachineManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VirtualMachineManagementServer will
// result in compilation errors.
type UnsafeVirtualMachineManagementServer interface {
	mustEmbedUnimplementedVirtualMachineManagementServer()
}

func RegisterVirtualMachineManagementServer(s grpc.ServiceRegistrar, srv VirtualMachineManagementServer) {
	s.RegisterService(&VirtualMachineManagement_ServiceDesc, srv)
}

func _VirtualMachineManagement_VirtualMachinePowerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtualMachinePowerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualMachineManagementServer).VirtualMachinePowerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vink.kubevm.io.apis.management.virtualmachine.v1alpha1.VirtualMachineManagement/VirtualMachinePowerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualMachineManagementServer).VirtualMachinePowerState(ctx, req.(*VirtualMachinePowerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VirtualMachineManagement_ServiceDesc is the grpc.ServiceDesc for VirtualMachineManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VirtualMachineManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vink.kubevm.io.apis.management.virtualmachine.v1alpha1.VirtualMachineManagement",
	HandlerType: (*VirtualMachineManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VirtualMachinePowerState",
			Handler:    _VirtualMachineManagement_VirtualMachinePowerState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "management/virtualmachine/v1alpha1/virtualmachine.proto",
}
