// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using VirtualMachinePowerStateRequest within kubernetes types, where deepcopy-gen is used.
func (in *VirtualMachinePowerStateRequest) DeepCopyInto(out *VirtualMachinePowerStateRequest) {
	p := proto.Clone(in).(*VirtualMachinePowerStateRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachinePowerStateRequest. Required by controller-gen.
func (in *VirtualMachinePowerStateRequest) DeepCopy() *VirtualMachinePowerStateRequest {
	if in == nil {
		return nil
	}
	out := new(VirtualMachinePowerStateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachinePowerStateRequest. Required by controller-gen.
func (in *VirtualMachinePowerStateRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
