/* eslint-disable */
// @ts-nocheck
/*
* This file is a generated Typescript file for GRPC Gateway, DO NOT MODIFY
*/

export enum ResourceType {
  UNSPECIFIED = "UNSPECIFIED",
  VIRTUAL_MACHINE = "VIRTUAL_MACHINE",
  VIRTUAL_MACHINE_INSTANCE = "VIRTUAL_MACHINE_INSTANCE",
  DATA_VOLUME = "DATA_VOLUME",
  NODE = "NODE",
  NAMESPACE = "NAMESPACE",
  MULTUS = "MULTUS",
  SUBNET = "SUBNET",
  VPC = "VPC",
  IPPOOL = "IPPOOL",
  STORAGE_CLASS = "STORAGE_CLASS",
  IPS = "IPS",
  VIRTUAL_MACHINE_SUMMARY = "VIRTUAL_MACHINE_SUMMARY",
}