// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for ListWatchRequest
func (this *ListWatchRequest) MarshalJSON() ([]byte, error) {
	str, err := ListwatchMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ListWatchRequest
func (this *ListWatchRequest) UnmarshalJSON(b []byte) error {
	return ListwatchUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for ListWatchResponse
func (this *ListWatchResponse) MarshalJSON() ([]byte, error) {
	str, err := ListwatchMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for ListWatchResponse
func (this *ListWatchResponse) UnmarshalJSON(b []byte) error {
	return ListwatchUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ListwatchMarshaler   = &jsonpb.Marshaler{}
	ListwatchUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
