// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: management/resource/v1alpha1/listwatch.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	types "github.com/kubevm.io/vink/apis/types"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = types.ResourceType(0)
)

// Validate checks the field values on ListWatchRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListWatchRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListWatchRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListWatchRequestMultiError, or nil if none found.
func (m *ListWatchRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListWatchRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ResourceType

	if all {
		switch v := interface{}(m.GetOptions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListWatchRequestValidationError{
					field:  "Options",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListWatchRequestValidationError{
					field:  "Options",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOptions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListWatchRequestValidationError{
				field:  "Options",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListWatchRequestMultiError(errors)
	}

	return nil
}

// ListWatchRequestMultiError is an error wrapping multiple validation errors
// returned by ListWatchRequest.ValidateAll() if the designated constraints
// aren't met.
type ListWatchRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListWatchRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListWatchRequestMultiError) AllErrors() []error { return m }

// ListWatchRequestValidationError is the validation error returned by
// ListWatchRequest.Validate if the designated constraints aren't met.
type ListWatchRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListWatchRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListWatchRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListWatchRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListWatchRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListWatchRequestValidationError) ErrorName() string { return "ListWatchRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListWatchRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListWatchRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListWatchRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListWatchRequestValidationError{}

// Validate checks the field values on ListWatchResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListWatchResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListWatchResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListWatchResponseMultiError, or nil if none found.
func (m *ListWatchResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListWatchResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventType

	if all {
		switch v := interface{}(m.GetDeleted()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListWatchResponseValidationError{
					field:  "Deleted",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListWatchResponseValidationError{
					field:  "Deleted",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeleted()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListWatchResponseValidationError{
				field:  "Deleted",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetOptions()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListWatchResponseValidationError{
					field:  "Options",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListWatchResponseValidationError{
					field:  "Options",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOptions()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListWatchResponseValidationError{
				field:  "Options",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListWatchResponseMultiError(errors)
	}

	return nil
}

// ListWatchResponseMultiError is an error wrapping multiple validation errors
// returned by ListWatchResponse.ValidateAll() if the designated constraints
// aren't met.
type ListWatchResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListWatchResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListWatchResponseMultiError) AllErrors() []error { return m }

// ListWatchResponseValidationError is the validation error returned by
// ListWatchResponse.Validate if the designated constraints aren't met.
type ListWatchResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListWatchResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListWatchResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListWatchResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListWatchResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListWatchResponseValidationError) ErrorName() string {
	return "ListWatchResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListWatchResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListWatchResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListWatchResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListWatchResponseValidationError{}
