// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using ListWatchRequest within kubernetes types, where deepcopy-gen is used.
func (in *ListWatchRequest) DeepCopyInto(out *ListWatchRequest) {
	p := proto.Clone(in).(*ListWatchRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListWatchRequest. Required by controller-gen.
func (in *ListWatchRequest) DeepCopy() *ListWatchRequest {
	if in == nil {
		return nil
	}
	out := new(ListWatchRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListWatchRequest. Required by controller-gen.
func (in *ListWatchRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ListWatchResponse within kubernetes types, where deepcopy-gen is used.
func (in *ListWatchResponse) DeepCopyInto(out *ListWatchResponse) {
	p := proto.Clone(in).(*ListWatchResponse)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListWatchResponse. Required by controller-gen.
func (in *ListWatchResponse) DeepCopy() *ListWatchResponse {
	if in == nil {
		return nil
	}
	out := new(ListWatchResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ListWatchResponse. Required by controller-gen.
func (in *ListWatchResponse) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
