// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using GetRequest within kubernetes types, where deepcopy-gen is used.
func (in *GetRequest) DeepCopyInto(out *GetRequest) {
	p := proto.Clone(in).(*GetRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetRequest. Required by controller-gen.
func (in *GetRequest) DeepCopy() *GetRequest {
	if in == nil {
		return nil
	}
	out := new(GetRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GetRequest. Required by controller-gen.
func (in *GetRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using CreateRequest within kubernetes types, where deepcopy-gen is used.
func (in *CreateRequest) DeepCopyInto(out *CreateRequest) {
	p := proto.Clone(in).(*CreateRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreateRequest. Required by controller-gen.
func (in *CreateRequest) DeepCopy() *CreateRequest {
	if in == nil {
		return nil
	}
	out := new(CreateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CreateRequest. Required by controller-gen.
func (in *CreateRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using UpdateRequest within kubernetes types, where deepcopy-gen is used.
func (in *UpdateRequest) DeepCopyInto(out *UpdateRequest) {
	p := proto.Clone(in).(*UpdateRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateRequest. Required by controller-gen.
func (in *UpdateRequest) DeepCopy() *UpdateRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new UpdateRequest. Required by controller-gen.
func (in *UpdateRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using DeleteRequest within kubernetes types, where deepcopy-gen is used.
func (in *DeleteRequest) DeepCopyInto(out *DeleteRequest) {
	p := proto.Clone(in).(*DeleteRequest)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteRequest. Required by controller-gen.
func (in *DeleteRequest) DeepCopy() *DeleteRequest {
	if in == nil {
		return nil
	}
	out := new(DeleteRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new DeleteRequest. Required by controller-gen.
func (in *DeleteRequest) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
