// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "management/resource/v1alpha1/resource.proto" (package "vink.kubevm.io.apis.management.resource.v1alpha1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ResourceManagement } from "./resource";
import type { Empty } from "../../../google/protobuf/empty";
import type { DeleteRequest } from "./resource";
import type { UpdateRequest } from "./resource";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CustomResourceDefinition } from "../../../apiextensions/v1alpha1/custom_resource_definition";
import type { CreateRequest } from "./resource";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service vink.kubevm.io.apis.management.resource.v1alpha1.ResourceManagement
 */
export interface IResourceManagementClient {
    /**
     * @generated from protobuf rpc: Create(vink.kubevm.io.apis.management.resource.v1alpha1.CreateRequest) returns (vink.kubevm.io.apis.apiextensions.v1alpha1.CustomResourceDefinition);
     */
    create(input: CreateRequest, options?: RpcOptions): UnaryCall<CreateRequest, CustomResourceDefinition>;
    /**
     * @generated from protobuf rpc: Update(vink.kubevm.io.apis.management.resource.v1alpha1.UpdateRequest) returns (vink.kubevm.io.apis.apiextensions.v1alpha1.CustomResourceDefinition);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, CustomResourceDefinition>;
    /**
     * @generated from protobuf rpc: Delete(vink.kubevm.io.apis.management.resource.v1alpha1.DeleteRequest) returns (google.protobuf.Empty);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, Empty>;
}
/**
 * @generated from protobuf service vink.kubevm.io.apis.management.resource.v1alpha1.ResourceManagement
 */
export class ResourceManagementClient implements IResourceManagementClient, ServiceInfo {
    typeName = ResourceManagement.typeName;
    methods = ResourceManagement.methods;
    options = ResourceManagement.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Create(vink.kubevm.io.apis.management.resource.v1alpha1.CreateRequest) returns (vink.kubevm.io.apis.apiextensions.v1alpha1.CustomResourceDefinition);
     */
    create(input: CreateRequest, options?: RpcOptions): UnaryCall<CreateRequest, CustomResourceDefinition> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateRequest, CustomResourceDefinition>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Update(vink.kubevm.io.apis.management.resource.v1alpha1.UpdateRequest) returns (vink.kubevm.io.apis.apiextensions.v1alpha1.CustomResourceDefinition);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, CustomResourceDefinition> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRequest, CustomResourceDefinition>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Delete(vink.kubevm.io.apis.management.resource.v1alpha1.DeleteRequest) returns (google.protobuf.Empty);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
