// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package v1alpha1

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for CustomResourceDefinition
func (this *CustomResourceDefinition) MarshalJSON() ([]byte, error) {
	str, err := CustomResourceDefinitionMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for CustomResourceDefinition
func (this *CustomResourceDefinition) UnmarshalJSON(b []byte) error {
	return CustomResourceDefinitionUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	CustomResourceDefinitionMarshaler   = &jsonpb.Marshaler{}
	CustomResourceDefinitionUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
