// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: apiextensions/v1alpha1/custom_resource_definition.proto

package v1alpha1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CustomResourceDefinition with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CustomResourceDefinition) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CustomResourceDefinition with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CustomResourceDefinitionMultiError, or nil if none found.
func (m *CustomResourceDefinition) ValidateAll() error {
	return m.validate(true)
}

func (m *CustomResourceDefinition) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CustomResourceDefinitionValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CustomResourceDefinitionValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CustomResourceDefinitionValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Spec

	// no validation rules for Status

	if len(errors) > 0 {
		return CustomResourceDefinitionMultiError(errors)
	}

	return nil
}

// CustomResourceDefinitionMultiError is an error wrapping multiple validation
// errors returned by CustomResourceDefinition.ValidateAll() if the designated
// constraints aren't met.
type CustomResourceDefinitionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CustomResourceDefinitionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CustomResourceDefinitionMultiError) AllErrors() []error { return m }

// CustomResourceDefinitionValidationError is the validation error returned by
// CustomResourceDefinition.Validate if the designated constraints aren't met.
type CustomResourceDefinitionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CustomResourceDefinitionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CustomResourceDefinitionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CustomResourceDefinitionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CustomResourceDefinitionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CustomResourceDefinitionValidationError) ErrorName() string {
	return "CustomResourceDefinitionValidationError"
}

// Error satisfies the builtin error interface
func (e CustomResourceDefinitionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCustomResourceDefinition.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CustomResourceDefinitionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CustomResourceDefinitionValidationError{}
