// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using CustomResourceDefinition within kubernetes types, where deepcopy-gen is used.
func (in *CustomResourceDefinition) DeepCopyInto(out *CustomResourceDefinition) {
	p := proto.Clone(in).(*CustomResourceDefinition)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinition. Required by controller-gen.
func (in *CustomResourceDefinition) DeepCopy() *CustomResourceDefinition {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinition. Required by controller-gen.
func (in *CustomResourceDefinition) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
